// generated by GPT5.3/5.5 after god tier prompting (aka me reverse engineering the living hell
// out of Crunchyroll website web pack... pls don't tell crunchy that though :wink:)
(() => {
  const CHUNK_NAME = "webpackChunk_N_E";
  const MODULE_ID = 37786;

  function tryPatch() {
    const req = window.__dualSubsNextRequire;
    if (!req?.m?.[MODULE_ID]) return false;

    const mod = req(MODULE_ID);
    const auth = mod?.AuthorizeInterceptor;
    if (!auth || auth.__dualSubsPatched) return true;

    auth.__dualSubsPatched = true;
    window.__dualSubsAuthorizeInterceptor = auth;

    const originalAuthorize = auth.authorize;
    const originalRefresh = auth.refreshTokenIfNeeded;
    const originalOnTokenExpire = auth.onTokenExpire;

    auth.onTokenExpire = function (cb) {
      console.log("[dual-sub auth] onTokenExpire registered");

      return originalOnTokenExpire.call(this, async (...args) => {
        console.log("[dual-sub auth] getNewToken called", args);
        const result = await cb(...args);
        console.log("[dual-sub auth] getNewToken result", result);
        return result;
      });
    };

    auth.refreshTokenIfNeeded = async function (...args) {
      console.log("[dual-sub auth] refreshTokenIfNeeded", {
        accessToken: this.accessToken,
        expired: this.accessToken?.isExpired?.()
      });

      return originalRefresh.apply(this, args);
    };

    auth.authorize = async function (...args) {
      console.log("[dual-sub auth] authorize", args);
      const result = await originalAuthorize.apply(this, args);
      console.log("[dual-sub auth] authorize done", this.accessToken);
      return result;
    };

    console.log("[dual-sub auth] patched", auth);
    return true;
  }

  function captureRequire() {
    const chunks = window[CHUNK_NAME];
    if (!chunks || window.__dualSubsNextRequire) return;

    chunks.push([
      [Math.random()],
      {},
      (req) => {
        window.__dualSubsNextRequire = req;
        console.log("[dual-sub auth] captured require");
      }
    ]);
  }

  const timer = setInterval(() => {
    const chunks = window[CHUNK_NAME];
    if (!chunks) return;

    captureRequire();

    if (tryPatch()) {
      clearInterval(timer);
    }
  }, 50);

  window.addEventListener("cr-dual-sub-request", async (event) => {
    const detail = JSON.parse(event["detail"]);
    const {uid, type} = { ...detail };
    try {
      let result;

      switch (type) {
        case "GRAB_TOKEN": {
          if (__dualSubsAuthorizeInterceptor) {
            console.warn("[dual sub auth] sending token...");
          } else {
            console.warn("[dual sub auth] not ready yet");
          }
          result = __dualSubsAuthorizeInterceptor.accessToken.token ?? null;
          break;
        }
        default: {
          return;
        }
      }

      window.dispatchEvent(new CustomEvent("cr-dual-sub-response", {
        detail: { uid, result }
      }));
    } catch (e) {
      window.dispatchEvent(new CustomEvent("cr-dual-sub-response", {
        detail: { uid, error: String(e?.message ?? e), result: false }
      }));
    }
  });
})();