import browser from "webextension-polyfill";
import {dragging, ensureSubtitleOverlay, overlayText} from "./ui/overlay";
import {ensureSubtitleControlShell, setTooltipText, updateNotice, updateSubtitleDropdownOptions} from "./ui/controls";
import type {Preference} from "./data/preferences";
import type {SubtitleManifest} from "./data/subtitles";

let videoEl: HTMLVideoElement;

let lastRendered = "";
let currentCues: Cue[];
let lastInit: string | null = null;

addMsgListener();

init().then().catch(r => {
  console.error(`[dual-sub] failed to init extension on ${location.href}`);
  console.error(r);
});

export async function updateCues(refresh = false) {
  if (refresh) {
    currentCues = (await browser.runtime.sendMessage({type: "GET_CUES", refresh})
      .catch(r => console.warn(r))) as Cue[];
  } else currentCues = await grabCues();
}

async function grabCues() {
  return (await browser.runtime.sendMessage({type: "GET_CUES"}).catch(r => console.warn(r))) as Cue[];
}

async function grabSubManifest() {
  return (await browser.runtime.sendMessage({type: "GET_CHOICES"}).catch(r => console.warn(r))) as SubtitleManifest;
}

export async function grabPreference(): Promise<Preference> {
  return (await browser.runtime.sendMessage({type: "GET_PREFERENCE"})) as Preference
}

function log(...data: any[]) {
  console.log("[dual-sub]", `${getCallerName()}:`, ...data);
}

function getCallerName() {
  // generated by Google Search AI
  const obj = {};
  // The second argument (getCallerName) tells V8 to hide this
  // function and everything above it from the trace.
  // @ts-ignore
  Error.captureStackTrace(obj, getCallerName);

  // The first line is 'Error', the second line is the actual caller.
  const stackLines = (obj as any).stack.split('\n');
  const callerLine = stackLines[2];

  // Extract function name using regex
  const match = /at (\S+)/.exec(callerLine);
  return match ? match[1] : 'anonymous';
}

function addMsgListener() {
  browser.runtime.onMessage.addListener(async (msg: any) => {
    switch (msg?.type) {
      case "REFRESH_CUES":
        currentCues = msg.cues;
        log(`refreshed cues (${currentCues.length} loaded)`);
        init().then().catch(r => {
          console.error(`[dual-sub] failed to (re)init extension on ${location.href}`);
          console.error(r);
        });
        return true;
      case "TRY_HACK":
        await tryHackToRefreshToken();
        return true;
      case "TAB_ID":
        return sessionStorage.getItem("cx-tab-id");
      case "FETCH_SUBTITLE":
        log("fetching subtitle in content script");
        const response = await fetch(msg.url);
        if (!response || !response.ok) return "";
        return await response.text();
      case "UPDATE_AVAILABLE":
        if (updateNotice) {
          updateNotice.classList.add("visible");
          setTooltipText(updateNotice, `Update available: ${browser.runtime.getManifest().version} → ${msg.version}`);
        }
        break;
      case "CLEAR_CUES":
        currentCues = [];
        log("received clear cues message from background.");
        break;
      case "UPDATE_PREFERENCE":
        log("updating preferences from popup");
        await updateDropdownOptions();
        await updateCues(true);
        break;
    }
  });
  log("added msg listener");
}

async function updateDropdownOptions() {
  log("updating sub choices...");
  const manifest = await grabSubManifest();
  const pref = await grabPreference();
  log("pref is", pref);
  log("manifest is", manifest);
  updateSubtitleDropdownOptions(manifest, pref);
  log("updated sub choices");
}

async function init() {
  if (lastInit === location.href) {
    log("skipping double init");
    await updateDropdownOptions();
    return;
  }
  log(`init begin on ${location.href}`);
  lastInit = location.href;
  if (await shouldSkip()) {
    log("not a watch page (probably)");
    return Promise.reject("[dual-sub] skipping, not a watch page (probably)");
  }
  log("not skipping, searching for player");
  let vid = getVideo();
  let counter = 4;
  while (!vid && counter-- > 0) {
    await sleep(1000);
    vid = getVideo();
  }
  if (!vid) {
    console.warn(`skipping because video player is not found`);
    return Promise.reject(`failed and skipping init on ${location.href}, could not find video player`);
  }

  videoEl = vid as HTMLVideoElement;

  log(`player found, injecting...`);
  ensurePageInjections();
  log("done, grabbing cues in 3s...");
  await sleep(3000);
  await updateCues(true);
  if (currentCues == null) {
    console.warn("failed to grab cues!");
    if (confirm("[Crunchyroll Dual Sub] Could not retrieve subtitle data. Please try refreshing or use the refresh button after a few moments.")) {
      await browser.runtime.sendMessage({type: "REFRESH_TAB"});
    }
    return Promise.reject("failed to grab cues");
  }

  log(`grabbed ${currentCues.length} cues`, currentCues);
  log("updating subtitle dropdown...");
  await updateDropdownOptions();
  log("done, starting subtitle render loop...");
  requestAnimationFrame(renderLoop);
  log("subtitle render loop started!");
  log("init complete!");
}

async function renderLoop() {
  if (await shouldSkip()) {
    log("[dual-sub] stopping render loop");
    return;
  }
  if (!videoEl || !overlayText) {
    console.error("[dual-sub] overlay or video doesn't exist while rendering");
    return;
  }

  const time = videoEl.currentTime;

  const secondaryCue = getActiveCue(currentCues, time);
  const nextText = dragging ? "(right click to reset)" : (secondaryCue?.text || "");

  if (!nextText || nextText !== lastRendered) {
    overlayText.textContent = nextText || "";
    overlayText.style.display = nextText && nextText.length > 0 ? "block" : "none";
    lastRendered = nextText;
  }

  // subtitleControl.innerText = "HI NICE TO MEET YOU"

  requestAnimationFrame(renderLoop);
}

async function shouldSkip() {
  let url: string = location.href;
  if (!url || !url.includes("/watch/")) {
    lastInit = null;
    log(`skipping ${location.href} because the top url is not a watch page`);
    return true;
  }
  return false;
}

function getVideo() {
  return document.querySelector("video") || document.querySelector("iframe")?.contentDocument?.querySelector("video");
}

function ensurePageInjections() {
  ensureSubtitleOverlay(videoEl);
  log("injected overlay");
  ensureSubtitleControlShell();
  log("injected subtitle control");
}

function getActiveCue(cues: Cue[], time: number): Cue | null {
  if (cues.length === 0) return null;
  if (compare(cues[0]!, time) == 0)
    return cues[0] ?? null;
  if (compare(cues[cues.length - 1]!, time) == 0)
    return cues[cues.length - 1] ?? null;

  let index = cues.length / 2;
  let prev = 0;
  let cue: Cue | undefined;
  let comp: number;
  while ((cue = cues[Math.floor(index)]) && (comp = compare(cue, time)) != 0) {
    let diff = Math.abs((index - prev) / 2);
    const nextIndex = comp > 0 ? index - diff : index + diff;
    if (Math.floor(nextIndex) === Math.floor(index)) break;
    prev = index;
    index = nextIndex;
  }
  if (!cue || compare(cue, time) != 0) {
    return null;
  }
  return cue;
}

function compare(cue: Cue, time: number): 0 | -1 | 1 {
  if (cue.start > time || cue.end < time)
    return cue.start > time ? 1 : -1;
  else return 0;
}

function sleep(ms: number) {
  return new Promise((resolve) => {
    setTimeout(resolve, ms);
  });
}

async function tryHackToRefreshToken() {
  // this seems to trigger a play head request that contains auth headers, in case
  // the background script is asleep at this point
  const wasPaused = videoEl.paused;
  if (wasPaused) {
    await videoEl.play();
  } else {
    videoEl.pause();
  }
  await sleep(10);
  if (wasPaused) {
    videoEl.pause();
  } else {
    await videoEl.play();
  }
  await sleep(5000);
}

export interface Cue {
  id: number,
  start: number,
  end: number,
  text: string
}
