name: Deploy this extension

on:
  workflow_dispatch:

permissions:
  contents: write

env:
  # courtesy of https://stackoverflow.com/a/71158878
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  do-setup:
    name: Grab all the stuff we need
    runs-on: ubuntu-latest
    steps:
      - name: Checkout it out
        uses: actions/checkout@v6
        with:
          fetch-depth: '0'

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build it (Firefox)
        run: BROWSER=firefox npm run build

      - name: Build it (Chrome)
        run: BROWSER=chrome npm run build

      - name: Grab project version
        id: version
        run: echo "version=$(npm pkg get version --workspaces=false | jq -r .)" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v7
        name: Upload the chrome extension archive
        with:
          path: 'dist-zip/cr-dual-subs-chrome.zip'
          name: "cr-dual-subs-chrome-${{ steps.version.outputs.version }}.zip"
          if-no-files-found: 'error'

      - uses: actions/upload-artifact@v7
        name: Upload the firefox extension archive
        with:
          path: 'dist-zip/cr-dual-subs-firefox.zip'
          name: "cr-dual-subs-firefox-${{ steps.version.outputs.version }}.zip"
          if-no-files-found: 'error'

      - name: Git archive dat thing
        run: git archive --format=zip --output=./cr-dual-subs-src.zip HEAD

      - uses: actions/upload-artifact@v7
        name: Upload the src archive
        with:
          path: 'cr-dual-subs-src.zip'
          name: "cr-dual-subs-src-${{ steps.version.outputs.version }}.zip"
          if-no-files-found: 'error'

      - name: Get last successful deploy commit
        id: last_success
        uses: nickderobertis/last-successful-commit-action@v1
        with:
          branch: ${{ env.BRANCH_NAME }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          workflow-id: 'deploy.yml'

      # courtesy of GPT-5.3 (or .2?)
      - name: Generate release notes
        id: notes
        run: |
          {
            echo "markdown<<EOF"
            echo "# ${{ steps.version.outputs.version }}"
            git log ${{ steps.last_success.outputs.commit-sha }}..HEAD \
              --pretty=format:'- %s'
            echo
            echo "EOF"
          } >> $GITHUB_OUTPUT

      - name: Throw stuff in the summary
        run: |
          echo "## The stuff we grabbed" >> $GITHUB_STEP_SUMMARY
          echo "> Last commit hash: ${{ steps.last_success.outputs.commit-sha }}" >> $GITHUB_STEP_SUMMARY
          echo "##${{ steps.notes.outputs.markdown }}" >> $GITHUB_STEP_SUMMARY
    outputs:
      notes: ${{ steps.notes.outputs.markdown }}
      version: ${{ steps.version.outputs.version }}

  push-changelog:
    name: Update CHANGELOG.md
    runs-on: ubuntu-latest
    needs:
      - do-setup
    steps:
      - uses: actions/checkout@v6
        name: Check it out!

      # apply the github-action bot email and username
      - uses: qoomon/actions--setup-git@v1
        name: Oooooh who am I
        with:
          user: bot

      - name: Prepend the CHANGELOG.md file
        # courtesy of https://stackoverflow.com/a/27950358
        run: |
          printf '%s\n\n%s\n' "${{ needs.do-setup.outputs.notes }}" "$(cat CHANGELOG.md)" > CHANGELOG.md

      - name: PUSH IT TO PROD
        run: |
          git add CHANGELOG.md
          git commit -m "Update changelog for ${{ needs.do-setup.outputs.version }}"
          git push

  deploy-firefox:
    name: Deploy addon to firefox
    runs-on: ubuntu-latest
    needs:
      - do-setup
      - push-changelog
    steps:
      - uses: actions/download-artifact@v8
        name: Download the built stuff

      - name: Try list file structure
        run: tree

      - uses: browser-actions/release-firefox-addon@latest
        name: Release it to firefox
        id: release
        with:
          addon-id: 'cr-dual-sub@andynoob'
          addon-path: "./cr-dual-subs-firefox-${{ needs.do-setup.outputs.version }}.zip/cr-dual-subs-firefox.zip"
          source-path: "./cr-dual-subs-src-${{ needs.do-setup.outputs.version }}.zip/cr-dual-subs-src.zip"
          auth-api-issuer: ${{ secrets.AMO_ISSUER }}
          auth-api-secret: ${{ secrets.AMO_SECRET }}
          license: MIT
          approval-note: |
            The steps to build project is in README.md.
          release-note: ${{ needs.do-setup.outputs.notes }}

      - name: Add stuff to summary
        run: |
          echo "## Firefox" >> $GITHUB_STEP_SUMMARY
          echo "Url is ${{ steps.release.outputs.version-edit-url }}" >> $GITHUB_STEP_SUMMARY

  deploy-github:
    name: Release it on GitHub
    runs-on: ubuntu-latest
    needs:
      - do-setup
      - push-changelog
    steps:
      - uses: actions/download-artifact@v8
        name: Download the built stuff

      - name: Try list file structure
        run: tree

      - uses: ncipollo/release-action@v1
        name: Release it on Github
        id: release
        with:
          artifacts: |
            ./cr-dual-subs-chrome-${{ needs.do-setup.outputs.version }}.zip/cr-dual-subs-chrome.zip
            ./cr-dual-subs-firefox-${{ needs.do-setup.outputs.version }}.zip/cr-dual-subs-firefox.zip
          body: ${{ needs.do-setup.outputs.notes }}
          commit: ${{ env.BRANCH_NAME }}
          tag: "v${{ needs.do-setup.outputs.version }}"
          allowUpdates: true
          artifactErrorsFailBuild: true

      - name: Add stuff to summary
        run: |
          echo "## Github" >> $GITHUB_STEP_SUMMARY
          echo "Url is ${{ steps.release.outputs.html_url }}" >> $GITHUB_STEP_SUMMARY

