name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy-firefox:
    name: Deploy addon to firefox
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci

      - name: Build it
        run: npm run build

      - name: Git archive it
        run: git archive --format=zip --output=./cr-dual-subs-src.zip HEAD
        
      - uses: yayuyokitano/firefox-addon@v0.0.6-alpha
        with:
          api_key: ${{ secrets.AMO_ISSUER }}
          api_secret: ${{ secrets.AMO_SECRET }}
          guid: '{cr-dual-sub@andynoob}'
          xpi_path: dist-zip/cr-dual-subs.zip
          src_path: cr-dual-subs-src.zip
