name: Deploy this extension

on:
  workflow_dispatch:

jobs:
  deploy-firefox:
    name: Deploy addon to firefox
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci

      - name: Grab project version
        id: version
        run: echo "version=$(npm pkg get version --workspaces=false | jq -r .)" >> $GITHUB_OUTPUT

      - name: "Extract changelog"
        id: changelog
        uses: sean0x42/markdown-extract@v2
        with:
          file: CHANGELOG.md
          pattern: ${{ steps.version.outputs.version }}

      - name: Build it
        run: npm run build

      - name: Git archive it
        run: git archive --format=zip --output=./cr-dual-subs-src.zip HEAD

      - uses: browser-actions/release-firefox-addon@latest
        with:
          addon-id: 'cr-dual-sub@andynoob'
          addon-path: 'dist-zip/cr-dual-subs.zip'
          source-path: 'cr-dual-subs-src.zip'
          auth-api-issuer: ${{ secrets.AMO_ISSUER }}
          auth-api-secret: ${{ secrets.AMO_SECRET }}
          license: 'MIT'
          approval-note: |
            The steps to build project is in README.md.
          release-note: ${{ steps.changelog.outputs.markdown }}
